controller:
  service:
    targetPorts:
      http: http
      https: http
    labels:
      dns: "route53"
    annotations:
      domainName: noga.one
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-1:472717593293:certificate/c2d544f0-1493-46a6-b106-ccac4875d587
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: 'tcp'
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
